[package]
name = "cacheForge"
version = "0.1.0"
edition = "2021"
authors = ["Samba Kolliboina"]
license = "MIT"
description = "A Cache library for rust applications"


[dependencies]
memory_box = { path = "../memory_box" }
cache_macro = { path = "../cache_macro" }
